framework:
    workflows:
        article:
            marking_store:
                type: property_accessor
            supports:
                - AppBundle\Entity\Article
            places:
                - draft
                - wait_for_journalist
                - approved_by_journalist
                - wait_for_spellchecker
                - approved_by_spellchecker
                - published
            transitions:
                request_review:
                    from:
                        - draft
                    to:
                        - wait_for_journalist
                        - wait_for_spellchecker
                journalist_approval:
                    from:
                        - wait_for_journalist
                    to:
                        - approved_by_journalist
                spellchecker_approval:
                    from:
                        - wait_for_spellchecker
                    to:
                        - approved_by_spellchecker
                publish:
                    from:
                        - approved_by_journalist
                        - approved_by_spellchecker
                    to:
                        - published
        order:
            marking_store:
                type: property_accessor
            supports:
                - AppBundle\Entity\Order
            places:
                - new_order
                - shipping_fee
                - delivery_fee
                - payed
                - server_validation
                - customer_informed
                - completed
            transitions:
                calculate_shipping_fee:
                    from:
                        - new_order
                    to:
                        - shipping_fee
                calculate_delivery_fee:
                    from: shipping_fee
                    to: delivery_fee
                pay:
                    from:
                        - delivery_fee
                    to:
                        - payed
                validate_order:
                    from:
                        - payed
                    to:
                        - server_validation
                inform_customer:
                    from:
                        - payed
                    to:
                        - customer_informed
                complete:
                    from:
                        - server_validation
                        - customer_informed
                    to:
                        - completed
